FROM postgres:16

# custom config to require authentication for connections from all origins
# COPY pg_hba.conf /var/lib/postgresql/data/pg_hba.conf


RUN apt-get update &&  \ 
    apt-get -y install postgresql-16-cron && \ 
    apt-get clean \ 
    && rm -rf /var/lib/apt/lists/


COPY 1-init.sql /docker-entrypoint-initdb.d/

COPY 2-schema.sql /docker-entrypoint-initdb.d/

COPY 3-permissions.sql /docker-entrypoint-initdb.d/

COPY 4-load.sql /docker-entrypoint-initdb.d/

COPY 5-functions.sql /docker-entrypoint-initdb.d/

COPY 6-cron_schedules.sql /docker-entrypoint-initdb.d/

COPY drop.sql /utils/

COPY pg_hba.conf /utils/



# RUN rm /var/lib/postgresql/data/pg_hba.conf && \
#     cp /utils/pg_hba.conf /var/lib/postgresql/data

# RUN cp /utils/pg_hba.conf /var/lib/postgresql/data/