FROM node:latest

WORKDIR /app
 
COPY package*.json ./
 
RUN npm install

COPY . .

RUN npm run dev

# Production Stage
# FROM nginx:latest AS production

# COPY --from=build /app/build /usr/share/nginx/html

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]
 
# EXPOSE 3000
 
# CMD ["npm", "start"]
